config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:new] do
    collection do
      post 'score', action: :score
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'net/http'
require 'json'

class GamesController < ApplicationController
  def new
    @letters = Array.new(10) { ('A'..'Z').to_a.sample }
  end

  def score
    @letters = params[:letters]
    @word = params[:word]

    @message = if !can_form_word?(@word, @letters)
                 "Sorry but, \"#{@word}\" can't be built off the letters."
               elsif !valid_english_word?(@word)
                 "Sorry but, \"#{@word}\" is not a valid English word."
               else
                 "Congratulations! \"#{@word}\" is a valid English word!"
               end
  end

  private

  def can_form_word?(word, letters)
    word.upcase.chars.all? { |char| word.upcase.count(char) <= letters.count(char) }
  end

  def valid_english_word?(word)
    url = "https://dictionary.lewagon.com/#{word}"
    response = Net::HTTP.get(URI(url))
    JSON.parse(response)['found']
  rescue StandardError => e
    Rails.logger.error "Error while checking word: #{e.message}"
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>Your Random Letters</h1>
<div class="letters-container">
  <% @letters.each do |letter| %>
    <div class="letter-box"><%= letter %></div>
  <% end %>
</div>

<div class="form-container">
  <%= form_with url: score_games_path, method: :post, local: true, data: { turbo: false } do |f| %>
    <p class="prompt">Text the longest word you can find!</p>

    <%= f.hidden_field :letters, value: @letters.join(',') %>
    <%= f.text_field :word, placeholder: "Enter your word", class: "word-input" %>
    <%= f.submit "Submit", class: "submit-button" %>
  <% end %>
</div>

app/views/games/score.html.erb
<h1>Result</h1>
<p><%= @message %></p>
<%= link_to "Play Again", new_game_path, class: "play-again-button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>